// qui dentro vanno inseriti gli script di creazione delle tabelle

-- -------------------------------------------------------------------------------------------------
-- FIRST VERSION
-- -------------------------------------------------------------------------------------------------


#RESTAURANT

CREATE TABLE `restaurant` (
  `Name` VARCHAR(45) NOT NULL COMMENT 'Restaurant name',
  `Address` VARCHAR(255) NOT NULL COMMENT 'Restaurant address',
  `Is_open` TINYINT(1) NOT NULL COMMENT 'Restaurant opening or closing.',
  `Seating_capacity` INT NOT NULL COMMENT 'Restaurant seating capacity',
  `Average_price` DOUBLE NOT NULL COMMENT 'Restaurant menu average price',
  `Recommended_dish` VARCHAR(45) NOT NULL COMMENT 'Restaurant best dish of the day',
  `Services` VARCHAR(255) NOT NULL COMMENT 'Restaurant services',
  `Has_home_delivery` TINYINT(1) NOT NULL COMMENT 'Restaurant presence of the delivery service',
  `Has_all_you_can_eat` TINYINT(1) NOT NULL COMMENT 'Restaurant presence of the all you can eat service',
  PRIMARY KEY (`Name`));


#CUSTOMER

CREATE TABLE `customer` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT 'Customer ID',
  `Name` VARCHAR(45) NOT NULL COMMENT 'Customer name',
  `Surname` VARCHAR(45) NULL COMMENT 'Customer surname',
  `Telephone_Number` VARCHAR(10) NOT NULL UNIQUE COMMENT 'Customer telephone number',
  `E_mail` VARCHAR(45) NOT NULL COMMENT 'Customer E-mail',
  `Group_size` INT NOT NULL COMMENT 'Number of people for the table',
  PRIMARY KEY (`Id`));

#DISH

CREATE TABLE `dish` (
  `Name` VARCHAR(45) NOT NULL COMMENT 'Dish name',
  `Course` VARCHAR(45) NOT NULL COMMENT 'Course type',
  `Ingredients` VARCHAR(255) NOT NULL COMMENT 'Dish ingredients',
  `Price` DOUBLE NOT NULL COMMENT 'Dish price',
  PRIMARY KEY (`Name`));

-- -------------------------------------------------------------------------------------------------
-- SECOND VERSION
-- -------------------------------------------------------------------------------------------------


-- MySQL Script generated by MySQL Workbench
-- Wed Jan 25 12:34:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurant` (
  `id_restaurant` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(64) NOT NULL,
  `restaurant_address` VARCHAR(64) NOT NULL,
  `seating_capacity` INT NOT NULL,
  `restaurant_avg_price` DECIMAL NOT NULL,
  `restaurant_recomm_dish` VARCHAR(64) NOT NULL,
  `restaurant_services` VARCHAR(64) NOT NULL,
  `has_home_delivery` TINYINT NOT NULL,
  `has_all_you_can_eat` TINYINT NOT NULL,
  `is_open` TINYINT NOT NULL,
  `tableservice` ENUM('buffet', 'a_la_carte') NOT NULL,
  PRIMARY KEY (`id_restaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `menu_preferences` ENUM('carnivorous', 'vegetarian', 'vegan', 'mixed') NOT NULL,
  `menu_based_on` ENUM('fish', 'meat', 'vegetable') NOT NULL,
  `menu_type_of_menu` ENUM('special', 'children', 'tasting', 'daily') NOT NULL,
  `restaurant_id_restaurant` INT NOT NULL,
  PRIMARY KEY (`id_menu`),
  INDEX `fk_menu_restaurant_idx` (`restaurant_id_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_menu_restaurant`
    FOREIGN KEY (`restaurant_id_restaurant`)
    REFERENCES `mydb`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dish` (
  `id_dish` INT NOT NULL AUTO_INCREMENT,
  `dish_name` VARCHAR(64) NOT NULL,
  `dish_course` VARCHAR(32) NOT NULL,
  `dish_ingredients` VARCHAR(255) NOT NULL,
  `dish_preferences` ENUM('carnivorous', 'vegetarian', 'vegan', 'mixed') NOT NULL,
  `dish_price` DECIMAL NOT NULL,
  `dish_dietary_options` ENUM('lactose_free', 'gluten_free', 'peanut_free', 'locally_produced') NOT NULL,
  `menu_id_menu` INT NOT NULL,
  PRIMARY KEY (`id_dish`),
  INDEX `fk_dish_menu1_idx` (`menu_id_menu` ASC) VISIBLE,
  CONSTRAINT `fk_dish_menu1`
    FOREIGN KEY (`menu_id_menu`)
    REFERENCES `mydb`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table` (
  `id_table` INT NOT NULL AUTO_INCREMENT,
  `table_seats_number` INT NOT NULL,
  `table_position` ENUM('indoor', 'outdoor') NOT NULL,
  `table_is_available` TINYINT NOT NULL,
  `restaurant_id_restaurant` INT NOT NULL,
  PRIMARY KEY (`id_table`),
  INDEX `fk_table_restaurant1_idx` (`restaurant_id_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_table_restaurant1`
    FOREIGN KEY (`restaurant_id_restaurant`)
    REFERENCES `mydb`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id_customer_table` INT NOT NULL AUTO_INCREMENT,
  `id_customer_generated` INT NOT NULL,
  `customer_name` VARCHAR(64) NOT NULL,
  `customer_surname` VARCHAR(64) NOT NULL,
  `customer_telephone` VARCHAR(32) NOT NULL,
  `customer_email` VARCHAR(64) NOT NULL,
  `customer_group_size` INT NOT NULL,
  `customer_preferences` ENUM('carnivorous', 'vegetarian', 'vegan', 'mixed') NOT NULL,
  PRIMARY KEY (`id_customer_table`),
  UNIQUE INDEX `id_customer_generated_UNIQUE` (`id_customer_generated` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firstcourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firstcourse` (
  `id_first_course` INT NOT NULL AUTO_INCREMENT,
  `first_course_is_pasta_fresca` TINYINT NOT NULL,
  `dish_id_dish` INT NOT NULL,
  PRIMARY KEY (`id_first_course`),
  INDEX `fk_firstcourse_dish1_idx` (`dish_id_dish` ASC) VISIBLE,
  CONSTRAINT `fk_firstcourse_dish1`
    FOREIGN KEY (`dish_id_dish`)
    REFERENCES `mydb`.`dish` (`id_dish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secondcourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secondcourse` (
  `id_second_course` INT NOT NULL AUTO_INCREMENT,
  `second_course_side_dish` VARCHAR(64) NOT NULL,
  `dish_id_dish` INT NOT NULL,
  PRIMARY KEY (`id_second_course`),
  INDEX `fk_secondcourse_dish1_idx` (`dish_id_dish` ASC) VISIBLE,
  CONSTRAINT `fk_secondcourse_dish1`
    FOREIGN KEY (`dish_id_dish`)
    REFERENCES `mydb`.`dish` (`id_dish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dessert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dessert` (
  `id_dessert` INT NOT NULL AUTO_INCREMENT,
  `dessert_is_home_made` TINYINT NOT NULL,
  `dish_id_dish` INT NOT NULL,
  PRIMARY KEY (`id_dessert`),
  INDEX `fk_dessert_dish1_idx` (`dish_id_dish` ASC) VISIBLE,
  CONSTRAINT `fk_dessert_dish1`
    FOREIGN KEY (`dish_id_dish`)
    REFERENCES `mydb`.`dish` (`id_dish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`drink` (
  `id_drink` INT NOT NULL AUTO_INCREMENT,
  `drink_alcoholic_volume` DECIMAL NOT NULL,
  `drink_is_alcoholic` TINYINT NOT NULL,
  `dish_id_dish` INT NOT NULL,
  PRIMARY KEY (`id_drink`),
  INDEX `fk_drink_dish1_idx` (`dish_id_dish` ASC) VISIBLE,
  CONSTRAINT `fk_drink_dish1`
    FOREIGN KEY (`dish_id_dish`)
    REFERENCES `mydb`.`dish` (`id_dish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `id_booking_table` INT NOT NULL AUTO_INCREMENT,
  `id_booking_generated` INT NOT NULL,
  `booking_date_time` DATETIME NOT NULL,
  `booking_group_size` INT NOT NULL,
  `customer_id_customer_table` INT NOT NULL,
  `restaurant_id_restaurant` INT NOT NULL,
  PRIMARY KEY (`id_booking_table`),
  INDEX `fk_booking_customer1_idx` (`customer_id_customer_table` ASC) VISIBLE,
  INDEX `fk_booking_restaurant1_idx` (`restaurant_id_restaurant` ASC) VISIBLE,
  CONSTRAINT `fk_booking_customer1`
    FOREIGN KEY (`customer_id_customer_table`)
    REFERENCES `mydb`.`customer` (`id_customer_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_restaurant1`
    FOREIGN KEY (`restaurant_id_restaurant`)
    REFERENCES `mydb`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_has_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_has_booking` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
